### ISSUE TITLE
[3DS] SDL 1.2  supported audio formats

### ISSUE THREAD

**Issue by MrHuu** [devkitPro/pacman-packages#110]
While working on OpenBOR for the 3DS, i ran into the issue that SDL 1.2 for 3DS didn't have support for the AUDIO_S16SYS format.

The audio formats are explained here:
[https://www.libsdl.org/release/SDL-1.2.15/docs/html/sdlaudiospec.html](https://www.libsdl.org/release/SDL-1.2.15/docs/html/sdlaudiospec.html)

To my understanding, both AUDIO_S16 and AUDIO_S16SYS will always point to AUDIO_S16LSB.

However, AUDIO_S16 is added as a supported format while AUDIO_S16SYS and AUDIO_S16LSB are not.

Can anyone more familiar with the matter give some insight if the format can be added as supported?
Or are there more related issues involved?

Would this cause any issues?
https://github.com/MrHuu/pacman-packages/commit/63f55a34a21e9ac803f2ced2e1879d2ef42c7696

**Comment by carstene1ns** [comment]
What you are observing should not really be possible, since these formats are not exposed to the platform drivers. This is done automatically: https://hg.libsdl.org/SDL/file/35a99e8ae9c4/include/SDL_audio.h#l96 (see lines 100-120).

However, 3DS port needs some revamps and cleanups, there is a branch here: https://github.com/devkitPro/SDL/tree/3ds-sdl-1.2

**Comment by MrHuu** [comment]
I see. I think i have to examine the requested audio specs more. 
I am able to init SDL_OpenAudio but SDL_CloseAudio fails.

But that's another issue, not related to this section.

I'll close this issue, and continue at the actual SDL branch when needed.
Thanks @carstene1ns
