### ISSUE TITLE
Pacman due for removal from Gentoo repos

### ISSUE THREAD

**Issue by pufchek** [devkitPro/pacman-packages#171]
Heyo! 
Not sure if this is the right repository to file this in(if it isn't, feel free to redirect me to the correct forum!)

I have recently set up devkitPro on Gentoo Linux, but while emerging I noticed the following for ``sys-apps/pacman`

![https://cdn.discordapp.com/attachments/585694938512097282/734925663236128788/07-20-2020-191136.png](https://cdn.discordapp.com/attachments/585694938512097282/734925663236128788/07-20-2020-191136.png)

For clarification, the notice refers to this bug report [https://bugs.gentoo.org/711134](https://bugs.gentoo.org/711134)

It seems there is no maintainer for ``pacman`` at the moment, and the package is slated for removal in 9 days, and wanted to see how this would affect any users wishing to install the toolchains on Gentoo systems.

Hope you're having a nice day by the way, and I enjoy the software you have put out so far! 😁

**Comment by WinterMute** [comment]
Did this get resolved in some way? Did someone step up to maintain it or has it just been removed now?

**Comment by pufchek** [comment]
Sorry for the late reply.

The package has been last-rited and removed from the official Gentoo repositories: https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=1229b2908e47bb2fed9cf77013f0440a421e1708

As to why I closed the issue, I took the lack of communication as a sign that this particular issue is beyond the scope of devkitPro as an entity

With it's removal, the wiki should be amended to reflect that, I think.

**Comment by carstene1ns** [comment]
The good thing is pacman is relatively easy to build on linux. Maybe it is worth to add some snap/appimage or such for other distributions.

**Comment by WinterMute** [comment]
> As to why I closed the issue, I took the lack of communication as a sign that this particular issue is beyond the scope of devkitPro as an entity.

Was more that I asked around to see if anyone used Gentoo & was willing to take it on but I got no response.

Pacman is relatively easy to build it's true but it has dependencies that I think are probably best managed by a distro's package manager rather than attempting to make a "runs anywhere" variant. We could, I guess, provide a custom ebuild in devkitPro repos & hope that someone might adopt it & get it back upstream. That will probably need someone familiar with portage to make sure we don't fluff it up.

> As always, thank you, devkitPro team, for providing amazing software.

Thanks for saying so. We often hear only about problems so it's always great to hear that there are people out there who appreciate the work we do.
