### ISSUE TITLE
Question: Help using cmake with external libraries

### ISSUE THREAD

**Issue by Nosh-Ware** [devkitPro/pacman-packages#286]
Not to sure if this is the right repo to ask but I see most of the cmake related definitions so I'm going to guess it is.
I have been trying to use the wii's <di/di.h> library for a while now along with cmake. I know that in a makefile the you simply need to add -ldi to LIBS and that's all you need. However, I have no idea how that works in cmake. Could I get some help?

For reference, here is my CMakeLists.txt
```
cmake_minimum_required(VERSION 3.12)
project ("tester" LANGUAGES CXX C VERSION 0.0.1)	
        file(GLOB helloworld_SRC
	"*/*.h"
	"*/*.c"
	"*/*.hpp"
	"*/*.cpp"
	)
	add_executable (${PROJECT_NAME} ${helloworld_SRC})
	ogc_create_dol(${PROJECT_NAME})
```

Also yes I know that using glob is heavily discouraged but it makes it easier for templates when I'm experimenting with projects like this.

**Comment by fincs** [comment]
This is an issue tracker for reporting problems/bugs and feature requests, not a support forum. For that there's the [devkitPro forums](https://devkitpro.org/).

In CMake you can just use [target_link_libraries](https://cmake.org/cmake/help/latest/command/target_link_libraries.html) like so: `target_link_libraries(${PROJECT_NAME} PRIVATE di)`

Fwiw, the minimum version of CMake that devkitPro supports is 3.13 (as shipped by Debian Buster), so you might want to bump that up in your CMakeLists.txt.

If using a GLOB, at least use [CONFIGURE_DEPENDS](https://cmake.org/cmake/help/latest/command/file.html#glob) so that it knows to regenerate the buildsystem when the output of the glob changes.
