### ISSUE TITLE
devkitPPC freetype

### ISSUE THREAD

**Issue by bladeoner** [devkitPro/pacman-packages#81]
Hi there,

I updated devkitPPC from r32 to r35 using Pacman, after that when I tried to build Snes9x Gx (Wii build), then I get: ft2build.h no such file or directory

I installed all packages I used before:
ppc-bzip2 ppc-freetype ppc-libjpeg-turbo ppc-libogg ppc-libpng ppc-libvorbisidec ppc-mpg123 ppc-mxml ppc-pkg-config ppc-zlib

Any idea what could cause this?

Thanks in advance.

**Comment by WinterMute** [comment]
> Hi there,
> 
> I updated devkitPro from r32 to r35 using Pacman, after that when I tried to build Snes9x Gx (Wii build), then I get: ft2build.h no such file or directory

No you didn't. devkitPro is an organisation dedicated to providing tools and libraries for homebrew development. Given that you're attempting to compile Snes9x GX I'm able to figure out that you mean **devkitPPC**. Please stop doing this. devkitPPC is just one toolchain devkitPro maintains, just like Photoshop is only one piece of software produced by Adobe and Windows is only one of Microsoft's productions. Continuing to use "devkitPro" as some kind of catch all for every piece of software we maintain is offensive and undermines the work we do to make homebrew possible. 

The problem is most likely not using freetype-config to obtain cflags & libs, especially the former.

**Comment by WinterMute** [comment]
For clarity, add `` `freetype-config --cflags` `` to your CFLAGS and `` `freetype-config --libs` `` to the LIBS line in your makefile. Include the backticks as written - this evaluates the command & will insert the result in the variable.

**Comment by bladeoner** [comment]
Thank you for pointing me in the right direction and sorry for the misunderstanding I meant devkitPPC yes.

**Comment by bladeoner** [comment]
@WinterMute thank you for your help, this fixed the issue.

I found your instruction which made it a little bit more clear for me :)
https://devkitpro.org/wiki/portlibs

Don't understand me wrong, I know maintaining the tools is a lot of work, which is really appreciated by a lot of people, also if they don't say it. Without guys like you there wouldn't be any homebrew.

But I think we share the same thought: make great things happen.

Thanks again and enjoy your day/evening.
